# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pylint Code Analysis

# When should this workflow run?
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest # The workflow runs on a Linux server hosted by GitHub

    steps:
    - name: ğŸ“¥ Checkout code
      uses: actions/checkout@v4

    - name: ğŸ Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: ğŸ“¦ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: ğŸ•µï¸â€â™‚ï¸ Analyze code with Pylint
      run: |
        # Analyze the main script. 
        # The --exit-zero flag prevents the workflow from failing if the score is not 10/10.
        pylint tot_discord_bridge.py --exit-zero
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
